execute pathogen#infect()
set nocompatible
syntax on
set backspace=2
set laststatus=2
set shiftwidth=4
set softtabstop=4
set tabstop=8
set expandtab
set smarttab
set number
set mouse=a
set textwidth=79
set wrap
set listchars=tab:>-,trail:-
set list!
set colorcolumn=80
set cursorline
set background=dark
colorscheme solarized
filetype plugin indent on

" airline
set t_Co=256
let g:airline_powerline_fonts = 1
" fugitive
let g:airline#extensions#branch#enabled = 1

" NERDTree options
let NERDTreeAutoCenter = 1
let NERDTreeCaseSensitiveSort = 1
let NERDTreeHighlightCursorline = 1
let NERDTreeMouseMode = 1
" let NERDTreeIgnore=['.*\.o$']
" let NERDTreeIgnore+=['.*\~$']
" let NERDTreeIgnore+=['.*\.out$']
" let NERDTreeIgnore+=['.*\.so$', '.*\.a$']
" let NERDTreeIgnore+=['.*\.pyc$']
" let NERDTreeIgnore+=['.*\.class$']
"
" Key remaps
nmap <F2> :NERDTreeToggle<CR>
nmap <F3> :TagbarToggle<CR>
" vim-go
let g:go_fmt_autosave=0
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
autocmd BufNewFile,BufRead *.go setlocal smarttab expandtab tabstop=8 shiftwidth=2

let g:tagbar_type_go = {
      \ 'ctagstype' : 'go',
      \ 'kinds'     : [
      \ 'p:package',
      \ 'i:imports:1',
      \ 'c:constants',
      \ 'v:variables',
      \ 't:types',
      \ 'n:interfaces',
      \ 'w:fields',
      \ 'e:embedded',
      \ 'm:methods',
      \ 'r:constructor',
      \ 'f:functions'
      \ ],
      \ 'sro' : '.',
      \ 'kind2scope' : {
      \ 't' : 'ctype',
      \ 'n' : 'ntype'
      \ },
      \ 'scope2kind' : {
      \ 'ctype' : 't',
      \ 'ntype' : 'n'
      \ },
      \ 'ctagsbin'  : 'gotags',
      \ 'ctagsargs' : '-sort -silent'
      \ }

let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_no_function_highlight = 1

